version: '3.7'

services:
    mvrusprod_data:
        container_name: mvrusprod_data
        image: mysql:latest
        command: ["--default-authentication-plugin=mysql_native_password"]
        volumes:
            - ../data/mysql:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_DATABASE: mvrussia
            MYSQL_USER: mvrussia
            MYSQL_PASSWORD: XpZGPFxfD2fqzzxR
            MYSQL_PORT: 3306
            TZ: Europe/Moscow
        restart: always
        ipc: private
        cap_drop:
            - NET_ADMIN
            - SYS_ADMIN

    mvrusprod_app:
        container_name: mvrusprod_app
        build:
            context: ./app
            dockerfile: app.dockerfile
        image: mvrusprod_app:latest
        volumes:
            - ../web/app:/var/www/project:rw,cached
            - ../web/app/var:/var/www/project/var:rw
        restart: always
        ipc: private
        cap_drop:
            - NET_ADMIN
            - SYS_ADMIN
        depends_on:
            - mvrusprod_data

    mvrusprod_server:
        container_name: mvrusprod_server
        build:
            context: ./server
            dockerfile: server.dockerfile
        image: mvrusprod_server:latest
        volumes:
            - ../web/app/public:/var/www/project/public:ro
            - ../web/app/var/log/nginx:/var/log/nginx
        ports:
            - 127.0.0.1:8383:80
        restart: always
        ipc: private
        cap_drop:
            - NET_ADMIN
            - SYS_ADMIN
        depends_on:
            - mvrusprod_app
